import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createDefaultMakeDocsConfig, loadMakeDocsConfig } from "../src/config";
import { listProjectPersonas } from "../src/persona";
import { applyInstallPlan, planInstall } from "../src/install";
import { defaultSelections } from "../src/profile";
import { loadManifest } from "../src/manifest";
import { invokeOperation } from "../src/operations/registry";
import { createExecutionContext } from "../src/operations/context";
import { readRawStoreLedger, writeRawStoreLedger } from "./store-ledger-fixture";
const roots:string[]=[];
function root(){const value=mkdtempSync(path.join(os.tmpdir(),"make-docs-r4-persona-"));roots.push(value);return value;}
function config(target:string,text:string){mkdirSync(path.join(target,".make-docs"),{recursive:true});writeFileSync(path.join(target,".make-docs/config.yaml"),text);}
afterEach(()=>{vi.unstubAllEnvs();for(const value of roots.splice(0))rmSync(value,{recursive:true,force:true});});
async function ensure(target:string,surface="assets"){return invokeOperation("project.surface.ensure",{surface,targetRoot:target},createExecutionContext({surface:"test",cwd:target,writesAllowed:true}));}
async function install(target:string,harnesses={codex:true,"claude-code":true}){const selections=defaultSelections();selections.harnesses=harnesses;const plan=await planInstall({targetDir:target,selections,existingManifest:null});return applyInstallPlan({targetDir:target,plan,existingManifest:null});}
describe("W19 R4 personas and content-driven assets",()=>{
 it.each([undefined,"","# comment\n","{}\n","personas: []\n"])("keeps defaults without writes for %j",text=>{const target=root();if(text!==undefined)config(target,text);const before=readdirSync(target);const result=listProjectPersonas(target);expect(result.personas.map(({displaySources,builtin,...p})=>p)).toEqual(createDefaultMakeDocsConfig().personas);expect(result.personas.map(p=>p.slug)).toEqual(["user","maintainer"]);expect(readdirSync(target)).toEqual(before);expect(existsSync(path.join(target,"docs"))).toBe(false);});
 it("inherits display fields and retains explicit custom roles",()=>{const target=root();config(target,"personas:\n - slug: user\n   label: Reader\n - slug: developer\n   label: Engineer\n   description: Builds software.\n   primitive: maintainer\n");const result=listProjectPersonas(target);expect(result.personas.map(p=>p.slug)).toEqual(["user","maintainer","developer"]);expect(result.personas[0]).toMatchObject({label:"Reader",description:"People or agents that use the project.",primitive:"user",displaySources:{label:"configured",description:"shipped"}});expect(loadMakeDocsConfig(target).configuredPersonaSlugs).toEqual(["user","developer"]);});
 it.each(["null","~","personas: null","personas: {}","personas: [","personas:\n - slug: user\n   primitive: maintainer","personas:\n - slug: user\n - slug: user",...["project","archive","artifacts","library","playbooks","../escape"].map(slug=>`personas:\n - slug: ${slug}\n   label: Test\n   description: Test.\n   primitive: user`),"personas:\n - slug: reviewer\n   label: Reviewer\n   description: Reviews.\n   primitive: agent","personas:\n - slug: reviewer"])("rejects invalid config without rewriting %s",text=>{const target=root();config(target,text);expect(loadMakeDocsConfig(target).valid).toBe(false);expect(()=>listProjectPersonas(target)).toThrow();expect(readFileSync(path.join(target,".make-docs/config.yaml"),"utf8")).toBe(text);});
 it("does not read the Store for discovery",()=>{const target=root(),blocked=path.join(target,"blocked");writeFileSync(blocked,"untouched");vi.stubEnv("MAKE_DOCS_HOME",blocked);expect(listProjectPersonas(target).personas).toHaveLength(2);expect(readFileSync(blocked,"utf8")).toBe("untouched");expect(readdirSync(target)).toEqual(["blocked"]);});
 it.each([{codex:true,"claude-code":false},{codex:false,"claude-code":true},{codex:true,"claude-code":true}])("delivers selected routers and no empty children %j",async harnesses=>{const target=root();await install(target,harnesses);const names=[...(harnesses.codex?["AGENTS.md"]:[]),...(harnesses["claude-code"]?["CLAUDE.md"]:[])];expect(existsSync(path.join(target,"docs/assets"))).toBe(false);for(const name of names)expect(readFileSync(path.join(target,"docs",name),"utf8")).toContain(`Asset router files: ${names.join(", ")}`);expect(readdirSync(path.join(target,"docs")).some(p=>p.includes("-only"))).toBe(false);const ensured=await ensure(target,"artifacts");expect(ensured.value).toMatchObject({ensuredPath:"docs/assets",contentDestination:"docs/assets/project",contentDestinationExists:false});expect(readdirSync(path.join(target,"docs/assets")).sort()).toEqual(names.sort());expect(existsSync(path.join(target,"docs/artifacts"))).toBe(false);const ledger=readRawStoreLedger(target);await ensure(target);expect(readRawStoreLedger(target)).toBe(ledger);});
 it("refreshes declarations without creating absent assets",async()=>{const target=root();await install(target,{codex:true,"claude-code":false});const selections=defaultSelections();selections.harnesses={codex:false,"claude-code":true};let current=loadManifest(target)!;let plan=await planInstall({targetDir:target,selections,existingManifest:current,operation:"setup.reconfigure"});applyInstallPlan({targetDir:target,plan,existingManifest:current});expect(existsSync(path.join(target,"docs/assets"))).toBe(false);expect(readFileSync(path.join(target,"docs/CLAUDE.md"),"utf8")).toContain("Asset router files: CLAUDE.md");await ensure(target);selections.harnesses={codex:true,"claude-code":false};current=loadManifest(target)!;plan=await planInstall({targetDir:target,selections,existingManifest:current,operation:"setup.reconfigure"});applyInstallPlan({targetDir:target,plan,existingManifest:current});expect(readdirSync(path.join(target,"docs/assets"))).toEqual(["AGENTS.md"]);});
 it("normalizes former bootstrap assets on reviewed setup and stays idempotent",async()=>{const target=root();await install(target);await ensure(target);const legacy=loadManifest(target)!;for(const name of ["AGENTS.md","CLAUDE.md"])legacy.routerOwnership!.routers[`docs/assets/${name}`]!.routerClass="bootstrap";writeRawStoreLedger(target,legacy);const current=loadManifest(target)!;expect(current.routerOwnership!.routers["docs/assets/AGENTS.md"]!.routerClass).toBe("bootstrap");const plan=await planInstall({targetDir:target,selections:current.selections,existingManifest:current,operation:"setup.reconfigure"});applyInstallPlan({targetDir:target,plan,existingManifest:current});expect(loadManifest(target)!.routerOwnership!.routers["docs/assets/AGENTS.md"]!.routerClass).toBe("on-demand-surface");const ledger=readRawStoreLedger(target);await ensure(target);expect(readRawStoreLedger(target)).toBe(ledger);});
 it("adopts manually authored root instructions without losing project text",async()=>{
   const target=root();await install(target,{codex:true,"claude-code":false});mkdirSync(path.join(target,"docs/assets"));
   writeFileSync(path.join(target,"docs/assets/AGENTS.md"),"# Project asset notes\nKeep these notes.\n");
   await ensure(target);const after=readFileSync(path.join(target,"docs/assets/AGENTS.md"),"utf8");
   expect(after).toContain("# Project asset notes\nKeep these notes.\n");expect(after).toContain("<!-- make-docs:begin -->");
   expect(readdirSync(path.join(target,"docs/assets"))).toEqual(["AGENTS.md"]);const ledger=readRawStoreLedger(target);await ensure(target);expect(readRawStoreLedger(target)).toBe(ledger);expect(readFileSync(path.join(target,"docs/assets/AGENTS.md"),"utf8")).toBe(after);
 });

});
