import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import * as fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {buildSkillAdoptionReview,applySkillAdoptionReview,presentSkillAdoptionReview,verifySkillAdoption} from '../src/skills-adoption';
import {writeManifest} from '../src/manifest';
import {defaultSelections} from '../src/profile';
import {loadEffectiveSkillRegistry} from '../src/skill-registry';
import {applySkillRegistrySelectionMetadata} from '../src/skill-catalog';
import {PACKAGE_ROOT} from '../src/utils';
import {readInstallationManifest,readInstallationStatus,recoverInstallationOperation} from '../src/store/installation-state';
import {installMakeDocsTarget} from './helpers';
import {planSkillsOnlyInstall,applySkillsOnlyInstallPlan,planInstall,applyInstallPlan} from '../src/install';
import * as resolver from '../src/skill-resolver';
import type {InstallSelections} from '../src/types';

let temp:string,root:string,store:string,home:string;
const faults=vi.hoisted(()=>({link:false,fallback:false,driftPath:'',driftDestination:''}));
vi.mock('node:fs',async original=>{const actual=await original<typeof import('node:fs')>();return {...actual,unlinkSync:(...args:Parameters<typeof actual.unlinkSync>)=>{const result=actual.unlinkSync(...args);if(faults.driftPath && String(args[0])===faults.driftPath){actual.writeFileSync(faults.driftDestination,'concurrent no-op edit');faults.driftPath='';}return result;},symlinkSync:(...args:Parameters<typeof actual.symlinkSync>)=>{if(faults.link)throw new Error('interrupt before native link');if(faults.fallback)throw Object.assign(new Error('symlink unavailable'),{code:'EPERM'});return actual.symlinkSync(...args);}};});
const shared='.agents/skills/preflight',native='.claude/skills/preflight';
beforeEach(()=>{temp=fs.mkdtempSync(path.join(os.tmpdir(),'make-docs-adoption-'));root=path.join(temp,'project');store=path.join(temp,'store');home=path.join(temp,'home');fs.mkdirSync(root);fs.mkdirSync(home);vi.stubEnv('MAKE_DOCS_HOME',store);vi.stubEnv('HOME',home);vi.spyOn(os,'homedir').mockReturnValue(home);});
afterEach(()=>{faults.link=false;faults.fallback=false;faults.driftPath='';faults.driftDestination='';vi.restoreAllMocks();vi.unstubAllEnvs();fs.rmSync(temp,{recursive:true,force:true});});
function options(scope:InstallSelections['skillScope']='project') {const effectiveRegistry=loadEffectiveSkillRegistry({packageRoot:PACKAGE_ROOT});const selections=defaultSelections();selections.skills=true;selections.selectedSkills=['preflight'];selections.skillScope=scope;selections.harnesses={'codex':true,'claude-code':true};return {targetDir:root,selections:applySkillRegistrySelectionMetadata(selections,effectiveRegistry),adoptExisting:['preflight'],effectiveRegistry};}
function put(relative:string,body:string) {fs.mkdirSync(path.dirname(path.join(root,relative)),{recursive:true});fs.writeFileSync(path.join(root,relative),body);}
describe('reviewed first-party Skill adoption',()=>{
 it.each(['symlink','copy-mirror'] as const)('keeps canonical %s ownership after adoption, normal setup and skills sync',async mode=>{
   if(mode==='copy-mirror')vi.stubEnv('MAKE_DOCS_DISABLE_SKILL_SYMLINKS','1');
   const first=await buildSkillAdoptionReview(options());applySkillAdoptionReview(first,first.digest);
   let manifest=readInstallationManifest(root)!;
   const full=await planInstall({targetDir:root,selections:manifest.selections,existingManifest:manifest});
   applyInstallPlan({targetDir:root,plan:full,existingManifest:manifest});
   manifest=readInstallationManifest(root)!;
   expect(manifest.files[shared+'/SKILL.md'].ownershipClass).toBe('managed-snapshot');
   expect(manifest.files[native].ownershipClass).toBe('selected-skill');
   const beforeSync=structuredClone(manifest.files);
   const skills=await planSkillsOnlyInstall({targetDir:root,selections:manifest.selections,existingManifest:manifest,remove:false});
   applySkillsOnlyInstallPlan({targetDir:root,plan:skills,existingManifest:manifest});
   expect(readInstallationManifest(root)!.files).toEqual(beforeSync);
   const repeat=presentSkillAdoptionReview(await buildSkillAdoptionReview(options()));
   expect(repeat.changes).toEqual([]);expect(repeat.backups).toEqual([]);expect(repeat.blockers).toEqual([]);
   expect(repeat.ownership.every(change=>change.effect==='retain')).toBe(true);
   expect(repeat.status).toBe('unchanged');
 });
 it('reviews fresh targets without writes and binds the canonical target',async()=>{const a=await buildSkillAdoptionReview(options());expect(a.blockers).toEqual([]);expect(fs.readdirSync(root)).toEqual([]);expect(fs.existsSync(store)).toBe(false);expect((await buildSkillAdoptionReview(options())).digest).toBe(a.digest);const other=path.join(temp,'other');fs.mkdirSync(other);expect((await buildSkillAdoptionReview({...options(),targetDir:other})).digest).not.toBe(a.digest);expect(presentSkillAdoptionReview(a).nextAction).toContain('same target, scope, tools');});
 it.each(['project','global'] as const)('applies a complete fresh %s plan and repeats without changes',async scope=>{const review=await buildSkillAdoptionReview(options(scope));expect(review.blockers).toEqual([]);expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');expect(readInstallationManifest(root)!.selections.selectedSkills).toEqual(['preflight']);expect(readInstallationStatus(root).status).toBe('ready');expect(fs.existsSync(path.join(root,'.make-docs/state'))).toBe(false);const repeat=await buildSkillAdoptionReview(options(scope));expect(repeat.blockers).toEqual([]);expect(presentSkillAdoptionReview(repeat).status).toBe('unchanged');});
 it('backs up known changed bytes and restores missing declared files',async()=>{put(shared+'/SKILL.md','local old copy');const review=await buildSkillAdoptionReview(options());expect(review.blockers).toEqual([]);expect(review.backups).toHaveLength(1);expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');expect(fs.readFileSync(path.join(root,review.backups[0].destination),'utf8')).toBe('local old copy');});
 it('blocks unknown extras and conflicting copies without writes',async()=>{put(shared+'/SKILL.md','shared old');put(native+'/SKILL.md','native old');put(shared+'/unknown.txt','keep');const review=await buildSkillAdoptionReview(options());expect(review.blockers.join('\n')).toMatch(/Unknown extra file/);expect(review.blockers.join('\n')).toMatch(/Conflicting existing copies/);expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow();expect(fs.existsSync(store)).toBe(false);expect(fs.readFileSync(path.join(root,shared+'/unknown.txt'),'utf8')).toBe('keep');});
 it('rejects exact byte drift after review',async()=>{put(shared+'/SKILL.md','reviewed');const review=await buildSkillAdoptionReview(options());put(shared+'/SKILL.md','later edit');expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/changed/);expect(fs.readFileSync(path.join(root,shared+'/SKILL.md'),'utf8')).toBe('later edit');});
 it('refuses an unsafe parent without reading its tree',async()=>{const outside=path.join(temp,'outside');fs.mkdirSync(outside);fs.symlinkSync(outside,path.join(root,'.make-docs'));await expect(buildSkillAdoptionReview(options())).rejects.toThrow(/symlink|link|Unsafe/);expect(fs.readdirSync(outside)).toEqual([]);});
 it('accepts only recorded intermediate removals while preserving unknown arrivals',async()=>{put(native+'/SKILL.md','old');const review=await buildSkillAdoptionReview(options());expect(review.blockers).toEqual([]);fs.unlinkSync(path.join(root,native+'/SKILL.md'));fs.rmdirSync(path.join(root,native));expect(verifySkillAdoption(root,review,'progress')).toEqual([]);put(native+'/intruder.txt','keep');expect(verifySkillAdoption(root,review,'progress').join('\n')).toContain('intruder');});
 it.each(['resume','rollback'] as const)('recovers with %s after exact native tree removal',async action=>{put(native+'/SKILL.md','old native bytes');const review=await buildSkillAdoptionReview(options());faults.link=true;expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/interrupt before native link/);expect(fs.existsSync(path.join(root,native))).toBe(false);const status=readInstallationStatus(root);expect(status.status).toBe('recovery-required');const id='pendingOperation' in status ? (status.pendingOperation as {operation_id:string}).operation_id : '';faults.link=false;expect(recoverInstallationOperation(root,id,action,false).status).toBe(action==='resume'?'completed':'rolled-back');if(action==='rollback')expect(fs.readFileSync(path.join(root,native+'/SKILL.md'),'utf8')).toBe('old native bytes');else expect(fs.lstatSync(path.join(root,native)).isSymbolicLink()).toBe(true);});
 it('registers matching copied bytes with no file actions and exposes their owner',async()=>{await installMakeDocsTarget(root);const initial=await buildSkillAdoptionReview(options());const states={...initial.after,...initial.alternatives[native]};for(const [p,s] of Object.entries(states).sort(([a],[b])=>a.length-b.length)){if(!p.startsWith(shared)&&!p.startsWith(native))continue;if(s.kind==='directory')fs.mkdirSync(path.join(root,p),{recursive:true,mode:s.mode});if(s.kind==='file'){fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),Buffer.from(s.contentBase64!,'base64'),{mode:s.mode});}}const review=await buildSkillAdoptionReview(options());expect(review.blockers).toEqual([]);expect(review.plan.changes).toEqual([]);expect(presentSkillAdoptionReview(review).ownership.some(x=>x.effect==='register')).toBe(true);expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');expect(fs.lstatSync(path.join(root,native)).isDirectory()).toBe(true);const repeat=presentSkillAdoptionReview(await buildSkillAdoptionReview(options()));expect(repeat.status).toBe('unchanged');expect(repeat.currentOwner?.projectId).toBe(readInstallationManifest(root)!.projectId);expect(repeat.ownership.every(x=>x.effect==='retain')).toBe(true);});
 it('blocks an unavailable Store before fresh managed writes',async()=>{const review=await buildSkillAdoptionReview(options());fs.writeFileSync(store,'unavailable');expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow();expect(fs.readdirSync(root)).toEqual([]);});
 it('reviews and completes a same-Skill scope and tool change',async()=>{const first=await buildSkillAdoptionReview(options());applySkillAdoptionReview(first,first.digest);const nextOptions=options('global');nextOptions.selections.harnesses={'codex':true,'claude-code':true};const next=await buildSkillAdoptionReview(nextOptions);expect(next.blockers).toEqual([]);expect(applySkillAdoptionReview(next,next.digest).status).toBe('completed');expect(fs.existsSync(path.join(root,shared))).toBe(false);expect(fs.existsSync(path.join(root,native))).toBe(false);expect(fs.existsSync(path.join(home,'.agents/skills/preflight/SKILL.md'))).toBe(true);expect(fs.existsSync(path.join(home,'.claude/skills/preflight/SKILL.md'))).toBe(true);});
 it('clearly blocks mixed adoption and deselection before saving state',async()=>{const first=await buildSkillAdoptionReview(options());applySkillAdoptionReview(first,first.digest);const nextOptions=options();nextOptions.selections.selectedSkills=['archive-docs'];nextOptions.adoptExisting=['archive-docs'];const next=await buildSkillAdoptionReview(nextOptions);expect(next.blockers.join('\n')).toContain('cannot also deselect preflight');expect(presentSkillAdoptionReview(next).status).toBe('blocked');});
 it.each(['project','global'] as const)('uses only reviewed copy fallback bytes in %s scope',async scope=>{const review=await buildSkillAdoptionReview(options(scope));faults.fallback=true;expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');const base=scope==='project'?root:home;expect(fs.lstatSync(path.join(base,native)).isDirectory()).toBe(true);const ledger=readInstallationManifest(root)!;const key=scope==='project'?native:path.join(home,native);expect(ledger.files[key].skillExposure?.mode).toBe('copy-mirror');expect(presentSkillAdoptionReview(await buildSkillAdoptionReview(options(scope))).status).toBe('unchanged');});
 it('blocks another checkout owner of the selected global bytes',async()=>{const first=await buildSkillAdoptionReview(options('global'));applySkillAdoptionReview(first,first.digest);const other=path.join(temp,'other');fs.mkdirSync(other);const review=await buildSkillAdoptionReview({...options('global'),targetDir:other});expect(review.blockers.join('\n')).toContain('checkout owner');expect(presentSkillAdoptionReview(review).status).toBe('blocked');});
 it('binds scope, tools and selected Skills to distinct review digests',async()=>{const initial=await buildSkillAdoptionReview(options());const global=await buildSkillAdoptionReview(options('global'));const tools=options();tools.selections.harnesses['claude-code']=false;const selected=options();selected.selections.selectedSkills.push('archive-docs');for(const review of [global,await buildSkillAdoptionReview(tools),await buildSkillAdoptionReview(selected)])expect(review.digest).not.toBe(initial.digest);});
 it('rejects changed link, extra inventory and package identity under the apply gate',async()=>{const review=await buildSkillAdoptionReview(options());put(shared+'/new.txt','later');expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/changed/);fs.unlinkSync(path.join(root,shared+'/new.txt'));fs.rmdirSync(path.join(root,shared));fs.mkdirSync(path.dirname(path.join(root,native)),{recursive:true});fs.symlinkSync('/elsewhere',path.join(root,native));expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/changed/);fs.unlinkSync(path.join(root,native));expect(()=>applySkillAdoptionReview({...review,packageDigest:'0'.repeat(64)},review.digest)).toThrow(/package|identity|changed|digest/i);});
 it('invalidates review when this checkout gains installation ownership',async()=>{const review=await buildSkillAdoptionReview(options());await installMakeDocsTarget(root);expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/ownership changed/);});
 it('updates and removes adopted files through the normal lifecycle while preserving unrelated content',async()=>{const review=await buildSkillAdoptionReview(options());applySkillAdoptionReview(review,review.digest);const original=resolver.resolveSkillSource;vi.spyOn(resolver,'resolveSkillSource').mockImplementation(async(...args)=>{const result=await original(...args);return {...result,entryPointContent:result.entryPointContent+'\nUpdated shipped instruction.\n'};});let manifest=readInstallationManifest(root)!;const update=await planSkillsOnlyInstall({targetDir:root,selections:manifest.selections,existingManifest:manifest,remove:false});expect(update.actions.find(a=>a.relativePath===shared+'/SKILL.md')?.type).toBe('update');applySkillsOnlyInstallPlan({targetDir:root,plan:update,existingManifest:manifest});expect(fs.readFileSync(path.join(root,shared+'/SKILL.md'),'utf8')).toContain('Updated shipped instruction.');put('notes/keep.txt','unrelated');manifest=readInstallationManifest(root)!;const removal=await planSkillsOnlyInstall({targetDir:root,selections:manifest.selections,existingManifest:manifest,remove:true});applySkillsOnlyInstallPlan({targetDir:root,plan:removal,existingManifest:manifest});expect(fs.existsSync(path.join(root,shared+'/SKILL.md'))).toBe(false);expect(fs.readFileSync(path.join(root,'notes/keep.txt'),'utf8')).toBe('unrelated');});
 it.each(['skills','setup'] as const)('does not implicitly adopt exact unowned bytes during normal %s with missing files',async mode=>{await installMakeDocsTarget(root);const review=await buildSkillAdoptionReview(options());const entry=review.after[shared+'/SKILL.md'];put(shared+'/SKILL.md',Buffer.from(entry.contentBase64!,'base64').toString('utf8'));const manifest=readInstallationManifest(root)!;const input=options();input.selections.harnesses=manifest.selections.harnesses;const args={targetDir:root,selections:input.selections,existingManifest:manifest,remove:false,skillRegistry:input.effectiveRegistry.registry};const plan=mode==='skills'?await planSkillsOnlyInstall(args):await planInstall(args);expect(plan.actions.filter(a=>a.relativePath.startsWith(shared+'/')).every(a=>a.type==='skip-conflict')).toBe(true);if(mode==='setup')expect(()=>applyInstallPlan({targetDir:root,plan,existingManifest:manifest})).toThrow(/unresolved managed-file conflicts/);else applySkillsOnlyInstallPlan({targetDir:root,plan,existingManifest:manifest});expect(readInstallationManifest(root)!.files[shared+'/SKILL.md']).toBeUndefined();expect(fs.readdirSync(path.join(root,shared))).toEqual(['SKILL.md']);});
});


describe('standard native Skill layout adoption',()=>{
 it('blocks unowned retired content and cleans only reviewed empty retired parents',async()=>{
  put('.make-docs/agentics/skills/preflight/SKILL.md','unowned legacy');const blocked=await buildSkillAdoptionReview(options());expect(blocked.blockers.join(' ')).toContain('Unowned retired Skill content');expect(()=>applySkillAdoptionReview(blocked,blocked.digest)).toThrow(/Unowned retired/);expect(fs.readFileSync(path.join(root,'.make-docs/agentics/skills/preflight/SKILL.md'),'utf8')).toBe('unowned legacy');
  fs.rmSync(path.join(root,'.make-docs/agentics/skills/preflight'),{recursive:true});const empty=await buildSkillAdoptionReview(options());expect(empty.blockers).toEqual([]);expect(applySkillAdoptionReview(empty,empty.digest).status).toBe('completed');expect(fs.existsSync(path.join(root,'.make-docs/agentics'))).toBe(false);
 });
 it.each(['codex','claude-code'] as const)('installs only the selected project %s tree',async harness=>{
  const input=options(); input.selections.harnesses={codex:harness==='codex','claude-code':harness==='claude-code'};
  const review=await buildSkillAdoptionReview(input); expect(review.blockers).toEqual([]); expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');
  const selected=harness==='codex'?'.agents':'.claude', absent=harness==='codex'?'.claude':'.agents';
  expect(fs.lstatSync(path.join(root,selected,'skills/preflight')).isDirectory()).toBe(true); expect(fs.existsSync(path.join(root,absent))).toBe(false);
 });
 it('reviews both to Claude-only and back without self-links or lost bytes',async()=>{
  const initial=await buildSkillAdoptionReview(options());applySkillAdoptionReview(initial,initial.digest);
  const claude=options();claude.selections.harnesses={codex:false,'claude-code':true};
  const cut=await buildSkillAdoptionReview(claude);expect(cut.blockers).toEqual([]);expect(applySkillAdoptionReview(cut,cut.digest).status).toBe('completed');
  expect(fs.lstatSync(path.join(root,native)).isDirectory()).toBe(true);expect(fs.existsSync(path.join(root,shared))).toBe(false);
  const back=await buildSkillAdoptionReview(options());expect(back.blockers).toEqual([]);expect(applySkillAdoptionReview(back,back.digest).status).toBe('completed');
  expect(fs.lstatSync(path.join(root,shared)).isDirectory()).toBe(true);expect(presentSkillAdoptionReview(await buildSkillAdoptionReview(options())).status).toBe('unchanged');
 });
 it('accepts exact configured global native homes outside the user home',async()=>{
  const codex=path.join(temp,'custom-codex'),claude=path.join(temp,'custom-claude');fs.mkdirSync(codex);fs.mkdirSync(claude);vi.stubEnv('CODEX_HOME',fs.realpathSync(codex));vi.stubEnv('CLAUDE_CONFIG_DIR',fs.realpathSync(claude));
  const review=await buildSkillAdoptionReview(options('global'));expect(review.blockers).toEqual([]);expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');
  for(const dir of [codex,claude])expect(fs.readFileSync(path.join(dir,'skills/preflight/SKILL.md'))).toEqual(fs.readFileSync(path.join(home,shared,'SKILL.md')));
  expect(presentSkillAdoptionReview(await buildSkillAdoptionReview(options('global'))).status).toBe('unchanged');
 });
 it.each(['normal','no-op destination drift','link create interruption'] as const)('cuts over three old managed payloads with both tools and recorded Claude links: %s',async scenario=>{
  const input=options();input.selections.harnesses={codex:true,'claude-code':true};input.selections.selectedSkills=['preflight','software-factory','human-experience'];input.adoptExisting=[...input.selections.selectedSkills];input.selections=applySkillRegistrySelectionMetadata(input.selections,input.effectiveRegistry);
  const initial=await buildSkillAdoptionReview(input);expect(applySkillAdoptionReview(initial,initial.digest).status).toBe('completed');
  const ledger=readInstallationManifest(root)!; const old='.make-docs/agentics/skills';fs.mkdirSync(path.join(root,old),{recursive:true});
  for(const name of input.adoptExisting){const direct='.agents/skills/'+name,legacy=old+'/'+name;fs.renameSync(path.join(root,direct),path.join(root,legacy));const target=path.relative(path.dirname(path.join(root,direct)),path.join(root,legacy));
   const mode=name==='human-experience'?'copy-mirror':'symlink';if(mode==='symlink')fs.symlinkSync(target,path.join(root,direct));else fs.cpSync(path.join(root,legacy),path.join(root,direct),{recursive:true});
   for(const p of Object.keys(ledger.files))if(p.startsWith(direct+'/')){ledger.files[legacy+p.slice(direct.length)]=ledger.files[p];delete ledger.files[p];}
   ledger.files[direct]={hash:'legacy-native-proof',sourceId:'skill-exposure:codex:'+name,ownershipClass:'selected-skill',skillExposure:{skillName:name,installName:name,harness:'codex',scope:'project',canonicalPayloadPath:legacy,exposurePath:direct,symlinkTarget:target,preferredMode:'symlink',mode}};
  }
  for(const name of input.adoptExisting){const exposure='.claude/skills/'+name,canonicalPayloadPath=old+'/'+name,symlinkTarget='../../'+canonicalPayloadPath;fs.unlinkSync(path.join(root,exposure));fs.symlinkSync(symlinkTarget,path.join(root,exposure));
   const hashes:Record<string,string>={'human-experience':'6b8af995c3c3efcc04469e2ba21410a7e578b2c1e475b17ecf2915d76ffe49b8','preflight':'858fc79680dcbed8eaaf43b126b706306ca795e49414e5cc3ec336a3e141b196','software-factory':'c1f0218731328af6cd1fd1e280bd30ea1372314936bcef1bd532e948256f6f08'};
   ledger.files[exposure]={hash:hashes[name],sourceId:'skill-exposure:claude-code:'+name,ownershipClass:'selected-skill',skillExposure:{skillName:name,installName:name,harness:'claude-code',scope:'project',canonicalPayloadPath,exposurePath:exposure,symlinkTarget,preferredMode:'symlink',mode:'symlink',copyMirrorSource:canonicalPayloadPath}};
  }
  ledger.skillFiles=Object.keys(ledger.files).filter(p=>p.startsWith(old+'/')||p.startsWith('.agents/skills/')||p.startsWith('.claude/skills/'));writeManifest(root,ledger);
  const review=await buildSkillAdoptionReview(input);expect(review.blockers).toEqual([]);expect(presentSkillAdoptionReview(review).recoveryLimits.join(' ')).toContain('forward resume');expect(review.backups.length).toBeGreaterThan(0);
  for(const name of input.adoptExisting){const p='.claude/skills/'+name;expect(review.plan.afterLedger!.files[p].hash).not.toBe(ledger.files[p].hash);expect(review.plan.changes.filter(change=>change.path===p).map(change=>[change.before.kind,change.after.kind])).toEqual([['symlink','missing'],['missing','symlink']]);}
  const link=path.join(root,'.claude/skills/preflight'),oldTarget='../../.make-docs/agentics/skills/preflight';fs.unlinkSync(link);fs.symlinkSync('../../.agents/skills/preflight',link);const changedLink=await buildSkillAdoptionReview(input);expect(changedLink.blockers.join(' ')).toContain('Unsafe or wrong-target Skill link');expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/changed/);fs.unlinkSync(link);fs.symlinkSync(oldTarget,link);
  const unnamed=await buildSkillAdoptionReview({...input,adoptExisting:['human-experience','software-factory']});expect(unnamed.blockers.join(' ')).toContain('Legacy Skill preflight must be named');expect(unnamed.blockers.join(' ')).toContain('Protected managed or unselected adoption conflict: .claude/skills/preflight');
  const changedOwner=structuredClone(ledger);changedOwner.files['.claude/skills/preflight'].sourceId='skill-exposure:another-provider:preflight';writeManifest(root,changedOwner);expect((await buildSkillAdoptionReview(input)).blockers.join(' ')).toContain('Protected managed or unselected adoption conflict: .claude/skills/preflight');writeManifest(root,ledger);
  put(old+'/preflight/unknown.txt','keep');expect((await buildSkillAdoptionReview(input)).blockers.join(' ')).toContain('Unknown extra');expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/changed/);fs.rmSync(path.join(root,old,'preflight/unknown.txt'));
  put('.make-docs/agentics/plugins/keep.txt','plugin content');expect((await buildSkillAdoptionReview(input)).blockers.join(' ')).toContain('unrelated content');expect(fs.readFileSync(path.join(root,'.make-docs/agentics/plugins/keep.txt'),'utf8')).toBe('plugin content');fs.rmSync(path.join(root,'.make-docs/agentics/plugins'),{recursive:true});
  if(scenario==='no-op destination drift'){
   const destination=path.join(root,'.agents/skills/human-experience/SKILL.md'),bytes=fs.readFileSync(destination);faults.driftPath=path.join(fs.realpathSync(root),'.agents/skills/preflight');faults.driftDestination=destination;
   expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/Adoption input\/output changed/);expect(fs.existsSync(path.join(root,old,'preflight/SKILL.md'))).toBe(true);expect(readInstallationStatus(root).status).toBe('recovery-required');
   fs.writeFileSync(destination,bytes);const status=readInstallationStatus(root);if(!('pendingOperation' in status)||!status.pendingOperation||typeof status.pendingOperation!=='object'||!('operation_id' in status.pendingOperation)||typeof status.pendingOperation.operation_id!=='string')throw new Error('Missing pending operation');const id=status.pendingOperation.operation_id;expect(recoverInstallationOperation(root,id,'resume',false).status).toBe('completed');
  }else if(scenario==='link create interruption'){
   faults.link=true;expect(()=>applySkillAdoptionReview(review,review.digest)).toThrow(/interrupt before native link/);faults.link=false;expect(fs.existsSync(path.join(root,old,'preflight/SKILL.md'))).toBe(true);expect(fs.existsSync(path.join(root,'.claude/skills/preflight'))).toBe(false);
   const status=readInstallationStatus(root);if(!('pendingOperation' in status)||!status.pendingOperation||typeof status.pendingOperation!=='object'||!('operation_id' in status.pendingOperation)||typeof status.pendingOperation.operation_id!=='string')throw new Error('Missing pending operation');const id=status.pendingOperation.operation_id;expect(recoverInstallationOperation(root,id,'rollback',false).status).toBe('blocked');
   put('.claude/skills/preflight','later user edit');expect(()=>recoverInstallationOperation(root,id,'resume',false)).toThrow(/preserves changed files|changed/);expect(fs.readFileSync(path.join(root,'.claude/skills/preflight'),'utf8')).toBe('later user edit');fs.rmSync(path.join(root,'.claude/skills/preflight'));expect(recoverInstallationOperation(root,id,'resume',false).status).toBe('completed');
  }else expect(applySkillAdoptionReview(review,review.digest).status).toBe('completed');expect(fs.existsSync(path.join(root,'.make-docs/agentics'))).toBe(false);
  for(const name of input.adoptExisting){expect(fs.lstatSync(path.join(root,'.agents/skills',name)).isDirectory()).toBe(true);expect(fs.readlinkSync(path.join(root,'.claude/skills',name))).toBe('../../.agents/skills/'+name);}
  expect(Object.keys(readInstallationManifest(root)!.files).some(p=>p.startsWith(old+'/'))).toBe(false);const rawRepeat=await buildSkillAdoptionReview(input);const repeat=presentSkillAdoptionReview(rawRepeat);expect(repeat.status,JSON.stringify({before:rawRepeat.beforeLedger?.selections,after:rawRepeat.plan.afterLedger?.selections})).toBe('unchanged');
 });
});
